// <auto-generated />
namespace SIIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ColoqueiTipoPermissaonoPaciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColoqueiTipoPermissaonoPaciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201505292001475_Coloquei TipoPermissao no Paciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
