// <auto-generated />
namespace SIIS.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RetireiTipoPermissaoDoUserEColoqueiEmPaciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RetireiTipoPermissaoDoUserEColoqueiEmPaciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201505291958340_RetireiTipoPermissaoDoUserEColoqueiEmPaciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
